import * as React from 'react'

import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div className="flex justify-center h-screen w-screen items-center">
      <Head>
        <title>mrizkiaiman - NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p className="text-2xl font-bold">M. Rizki Aiman - NextJS Boilerplate 📝</p>
      </main>
      <footer />
    </div>
  )
}
