import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Next.js (v13.2) | create-mrizkiaiman-app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center items-center w-screen h-screen">
        <a href="https://www.mrizkiaiman.com" target="_blank">
          <p className="text-4xl text-orange-400 font-extrabold tracking-tighter">
            M. Rizki Aiman ✌🏻 <span className="text-gray-700">Next.js</span>
          </p>
        </a>
      </main>
    </>
  )
}
